-- PostgreSQL Script generated by MySQL Workbench
-- Sun Mar  9 15:33:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Disable foreign key checks and unique checks (PostgreSQL does not have these settings)
-- PostgreSQL does not have direct equivalents for these MySQL settings, so they are omitted.

-- -----------------------------------------------------
-- Schema toolkit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS "toolkit" AUTHORIZATION CURRENT_USER;

-- -----------------------------------------------------
-- Table "toolkit"."models"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "toolkit"."models" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(45) NOT NULL,
  "recipe_name" VARCHAR(45) NULL,
  "created_at" TIMESTAMP NOT NULL
);

INSERT INTO "toolkit"."models" ("name", "recipe_name", "created_at")
VALUES
('BM25', 'Elastic+BEIR', NOW()),
('FAISS Vector Store', 'sentence-transformers/all-MiniLM-L6-v2', NOW());


-- -----------------------------------------------------
-- Table "toolkit"."datasets"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "toolkit"."datasets" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(45) NOT NULL,
  "description" VARCHAR(255) NOT NULL, -- Increased length of description
  "created_at" TIMESTAMP NOT NULL,
  "type" VARCHAR(45) NOT NULL,
  "path" VARCHAR(3000) NULL,
  "corpus_size" INT NULL,
  "queries_size" INT NULL,
  "dev_size" INT NULL,
  "test_size" INT NULL,
  "downloaded_at" TIMESTAMP NULL
);

INSERT INTO "toolkit"."datasets" ("name", "description", "created_at", "type", "path", "corpus_size", "queries_size", "dev_size", "test_size", "downloaded_at")
VALUES
('MSMARCO', 'MSMARCO dataset', NOW(), 'BEIR', NULL, 8840000, 6980, NULL, NULL, NULL),
('TREC-COVID', 'TREC-COVID dataset', NOW(), 'BEIR', NULL, 171000, 50, NULL, NULL, NULL),
('NFCorpus', 'NFCorpus dataset', NOW(), 'BEIR', NULL, 3600, 323, NULL, NULL, NULL),
('NQ', 'Natural Questions dataset', NOW(), 'BEIR', NULL, 2680000, 3452, NULL, NULL, NULL),
('HotpotQA', 'HotpotQA dataset', NOW(), 'BEIR', NULL, 5230000, 7405, NULL, NULL, NULL),
('FiQA-2018', 'FiQA-2018 dataset', NOW(), 'BEIR', NULL, 57000, 648, NULL, NULL, NULL),
('ArguAna', 'ArguAna dataset', NOW(), 'BEIR', NULL, 8670, 1406, NULL, NULL, NULL),
('Touche-2020', 'Touche-2020 dataset', NOW(), 'BEIR', NULL, 382000, 49, NULL, NULL, NULL),
('CQADupstack', 'CQADupstack dataset', NOW(), 'BEIR', NULL, 457000, 13145, NULL, NULL, NULL),
('Quora', 'Quora dataset', NOW(), 'BEIR', NULL, 523000, 10000, NULL, NULL, NULL),
('DBPedia', 'DBPedia dataset', NOW(), 'BEIR', NULL, 4630000, 400, NULL, NULL, NULL),
('SCIDOCS', 'SCIDOCS dataset', NOW(), 'BEIR', NULL, 25000, 1000, NULL, NULL, NULL),
('FEVER', 'FEVER dataset', NOW(), 'BEIR', NULL, 5420000, 6666, NULL, NULL, NULL),
('Climate-FEVER', 'Climate-FEVER dataset', NOW(), 'BEIR', NULL, 5420000, 1535, NULL, NULL, NULL),
('SciFact', 'SciFact dataset', NOW(), 'BEIR', 'beir/scifact', 5000, 300, NULL, NULL, NULL);

-- Enable foreign key checks and unique checks (PostgreSQL does not have these settings)
-- PostgreSQL does not have direct equivalents for these MySQL settings, so they are omitted.

-- -----------------------------------------------------
-- Table "toolkit"."indexes"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "toolkit"."indexes" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(45) NOT NULL,
  "model_id" INT NOT NULL,
  "dataset_id" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "last_build_at" TIMESTAMP NULL,
  CONSTRAINT "model_fk"
    FOREIGN KEY ("model_id")
    REFERENCES "toolkit"."models" ("id"),
  CONSTRAINT "dataset_fk"
    FOREIGN KEY ("dataset_id")
    REFERENCES "toolkit"."datasets" ("id")
);

CREATE UNIQUE INDEX "id_UNIQUE" ON "toolkit"."indexes" ("id");
CREATE INDEX "model_idx" ON "toolkit"."indexes" ("model_id");

-- -----------------------------------------------------
-- View for making it easier to get data to create UI
-- -----------------------------------------------------
CREATE OR REPLACE VIEW "toolkit"."wide_indexes_view" AS
SELECT 
	i.*, 
	d."name" AS dataset_name, 
	d."path" AS dataset_path,
	d.corpus_size,
	d.dev_size,
	d.downloaded_at,
	m."name" AS model_name,
	m.recipe_name AS model_recipe_name,
	m.created_at AS model_created_at
FROM "toolkit"."indexes" i 
	LEFT JOIN "toolkit"."datasets" d ON i.dataset_id = d.id 
	LEFT JOIN "toolkit"."models" m ON i.model_id = m.id;